PATH:
    DATA_PATH: /private/liuzili/quantize/OneDrive_1_2019-5-10/obj_data

OUTPUT:
    WEIGHT_BIT_TABLE: ./obj_workdir/weight.table
    FEAT_BIT_TABLE: ./obj_workdir/feat.table
    WEIGHT_DIR: ./obj_workdir/weight
    BIAS_DIR: ./obj_workdir/bias
    FINAL_BIAS_DIR: ./obj_workdir/new_bias

SETTINGS:
    GPU: 0
    WORKER_NUM: 12
    INTERVAL_NUM: 2048
    STATISTIC: 1
    MAX_CALI_IMG_NUM: 400
    MAX_SHIFT: 12
    SUPPORT_DILATION: False
